-- MySQL Script generated by MySQL Workbench
-- mar 09 may 2017 18:04:40 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hoteles
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hoteles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hoteles` DEFAULT CHARACTER SET utf8 ;
USE `hoteles` ;

-- -----------------------------------------------------
-- Table `hoteles`.`hotels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteles`.`hotels` (
  `name` VARCHAR(125) NOT NULL,
  `provincias` VARCHAR(125) NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
